"""add pk to vendor_order

Revision ID: 157e51808b30
Revises: 839cf896b393
Create Date: 2025-12-09 15:12:54.527413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '157e51808b30'
down_revision: Union[str, None] = '839cf896b393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_orders', 'modified_by')
    op.drop_column('vendor_orders', 'inactive')
    op.drop_column('vendor_orders', 'deleted_at')
    op.drop_column('vendor_orders', 'created_by')
    op.drop_column('vendor_orders', 'created_at')
    op.drop_column('vendor_orders', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_orders', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('vendor_orders', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('vendor_orders', sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('vendor_orders', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.add_column('vendor_orders', sa.Column('inactive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('vendor_orders', sa.Column('modified_by', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
