"""create event manager profile 

Revision ID: 404ea9acd6c1
Revises: c5ce3c74bc8e
Create Date: 2025-12-12 14:57:43.412367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404ea9acd6c1'
down_revision: Union[str, None] = 'c5ce3c74bc8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_manager_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active_events_count', sa.Integer(), nullable=True),
    sa.Column('completed_events_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.String(length=50), nullable=True),
    sa.Column('max_concurrent_events', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_event_manager_profiles_id'), 'event_manager_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_manager_profiles_id'), table_name='event_manager_profiles')
    op.drop_table('event_manager_profiles')
    # ### end Alembic commands ###
