"""test detect

Revision ID: 47e78ad438ec
Revises: e1449e23b30c
Create Date: 2025-12-11 11:44:08.788511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e78ad438ec'
down_revision: Union[str, None] = 'e1449e23b30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_bids', sa.Column('timeline_days', sa.Integer(), nullable=True))
    op.add_column('vendor_bids', sa.Column('proposed_date', sa.DateTime(), nullable=True))
    op.add_column('vendor_bids', sa.Column('advantages', sa.JSON(), nullable=True))
    op.add_column('vendor_bids', sa.Column('requirements', sa.JSON(), nullable=True))
    op.add_column('vendor_bids', sa.Column('includes', sa.JSON(), nullable=True))
    op.add_column('vendor_bids', sa.Column('vendor_rating', sa.Float(), nullable=True))
    op.add_column('vendor_bids', sa.Column('vendor_experience', sa.String(length=50), nullable=True))
    op.add_column('vendor_bids', sa.Column('vendor_completed_events', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_bids', 'vendor_completed_events')
    op.drop_column('vendor_bids', 'vendor_experience')
    op.drop_column('vendor_bids', 'vendor_rating')
    op.drop_column('vendor_bids', 'includes')
    op.drop_column('vendor_bids', 'requirements')
    op.drop_column('vendor_bids', 'advantages')
    op.drop_column('vendor_bids', 'proposed_date')
    op.drop_column('vendor_bids', 'timeline_days')
    # ### end Alembic commands ###
