"""add icon to category

Revision ID: 5062c591664e
Revises: 900d434810b0
Create Date: 2025-12-09 15:04:31.608084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5062c591664e'
down_revision: Union[str, None] = '900d434810b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(length=255), nullable=True))
    op.alter_column('vendor_categories', 'vendor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('vendor_categories', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_categories', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('vendor_categories', 'vendor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
