"""added fields in vendor bid table

Revision ID: a6fc6f06503f
Revises: 7cdda776a123
Create Date: 2025-12-15 14:56:20.790827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6fc6f06503f'
down_revision: Union[str, None] = '7cdda776a123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'required_services',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('events', 'bidding_status',
               existing_type=mysql.ENUM('open', 'closed', 'under_review', 'shortlisted', 'awarded'),
               nullable=True,
               existing_server_default=sa.text("'open'"))
    op.add_column('vendor_bids', sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('vendor_bids', sa.Column('service_breakdown', sa.JSON(), nullable=True))
    op.add_column('vendor_bids', sa.Column('proposal_description', sa.Text(), nullable=True))
    op.add_column('vendor_bids', sa.Column('portfolio_items', sa.JSON(), nullable=True))
    op.add_column('vendor_bids', sa.Column('terms_and_conditions', sa.Text(), nullable=True))
    op.add_column('vendor_bids', sa.Column('cancellation_policy', sa.Text(), nullable=True))
    op.add_column('vendor_bids', sa.Column('admin_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vendor_bids', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('vendor_bids', sa.Column('shortlisted', sa.Boolean(), nullable=True))
    op.add_column('vendor_bids', sa.Column('shortlisted_rank', sa.Integer(), nullable=True))
    op.add_column('vendor_bids', sa.Column('admin_reviewed_by', sa.String(length=100), nullable=True))
    op.add_column('vendor_bids', sa.Column('admin_reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('vendor_bids', sa.Column('vendor_experience_years', sa.Integer(), nullable=True))
    op.add_column('vendor_bids', sa.Column('consumer_viewed_at', sa.DateTime(), nullable=True))
    op.add_column('vendor_bids', sa.Column('selected_at', sa.DateTime(), nullable=True))
    op.add_column('vendor_bids', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.alter_column('vendor_bids', 'event_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('vendor_bids', 'notes',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('vendor_bids', 'vendor_rating',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
    op.create_foreign_key(None, 'vendor_bids', 'events', ['event_id'], ['id'])
    op.drop_column('vendor_bids', 'requirements')
    op.drop_column('vendor_bids', 'includes')
    op.drop_column('vendor_bids', 'category_id')
    op.drop_column('vendor_bids', 'accepted_at')
    op.drop_column('vendor_bids', 'vendor_experience')
    op.drop_column('vendor_bids', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_bids', sa.Column('amount', mysql.FLOAT(), nullable=False))
    op.add_column('vendor_bids', sa.Column('vendor_experience', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('vendor_bids', sa.Column('accepted_at', mysql.DATETIME(), nullable=True))
    op.add_column('vendor_bids', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vendor_bids', sa.Column('includes', mysql.JSON(), nullable=True))
    op.add_column('vendor_bids', sa.Column('requirements', mysql.JSON(), nullable=True))
    op.drop_constraint(None, 'vendor_bids', type_='foreignkey')
    op.alter_column('vendor_bids', 'vendor_rating',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('vendor_bids', 'notes',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('vendor_bids', 'event_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('vendor_bids', 'rejected_at')
    op.drop_column('vendor_bids', 'selected_at')
    op.drop_column('vendor_bids', 'consumer_viewed_at')
    op.drop_column('vendor_bids', 'vendor_experience_years')
    op.drop_column('vendor_bids', 'admin_reviewed_at')
    op.drop_column('vendor_bids', 'admin_reviewed_by')
    op.drop_column('vendor_bids', 'shortlisted_rank')
    op.drop_column('vendor_bids', 'shortlisted')
    op.drop_column('vendor_bids', 'admin_notes')
    op.drop_column('vendor_bids', 'admin_score')
    op.drop_column('vendor_bids', 'cancellation_policy')
    op.drop_column('vendor_bids', 'terms_and_conditions')
    op.drop_column('vendor_bids', 'portfolio_items')
    op.drop_column('vendor_bids', 'proposal_description')
    op.drop_column('vendor_bids', 'service_breakdown')
    op.drop_column('vendor_bids', 'total_amount')
    op.alter_column('events', 'bidding_status',
               existing_type=mysql.ENUM('open', 'closed', 'under_review', 'shortlisted', 'awarded'),
               nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('events', 'required_services',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###
