"""vendor models update

Revision ID: db5dad59e96d
Revises: 030dd616d7e8
Create Date: 2025-12-09 13:46:30.467847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db5dad59e96d'
down_revision: Union[str, None] = '030dd616d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'categories')
    op.drop_column('vendors', 'service_areas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('service_areas', mysql.JSON(), nullable=True))
    op.add_column('vendors', sa.Column('categories', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
