"""add icon & description to category

Revision ID: e36f0d4dca8e
Revises: 96f5cf11c221
Create Date: 2025-12-09 15:23:03.079623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36f0d4dca8e'
down_revision: Union[str, None] = '96f5cf11c221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
